# VirtualHost del frontend en servidorUbuntu1
# Copiar a /etc/apache2/sites-available/apuestas.conf
# (cambiar midominio.net por el dominio configurado en el BIND del Taller 4)
<VirtualHost *:80>
    # Entrar por dominio
    ServerName www.midominio.net
    # Entrar por dominio sin www y por IP
    ServerAlias midominio.net 192.168.100.2

    DocumentRoot /var/www/apuestas
    DirectoryIndex index.html

    ErrorLog ${APACHE_LOG_DIR}/apuestas_error.log
    CustomLog ${APACHE_LOG_DIR}/apuestas_access.log combined
</VirtualHost>
